<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.7.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.7.3" />
    <PackageReference Include="DotNetWorkQueue" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Dashboard.Client" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.SQLite" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.LiteDb" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.Redis" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.SqlServer" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.PostgreSQL" Version="0.9.31" />
    <PackageReference Include="Npgsql" Version="8.0.8" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OpenTelemetry" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
    <PackageReference Include="SimpleInjector" Version="5.5.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="Stub.System.Data.SQLite.Core.NetFramework" Version="1.0.119" />
    <PackageReference Include="Polly.Caching.Memory" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SampleShared">
      <HintPath>..\SampleShared\bin\Debug\net10.0\SampleShared.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
</Project>
