<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>DashBoard.Api</AssemblyTitle>
    <Product>DashBoard.Api</Product>
    <Copyright>Copyright © 2026 Brian Lehnen</Copyright>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetWorkQueue.Dashboard.Api" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Dashboard.Ui" Version="0.9.31" />
    <PackageReference Include="MudBlazor" Version="9.1.0" />
    <PackageReference Include="DotNetWorkQueue.Transport.PostgreSQL" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.SqlServer" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.SQLite" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.LiteDb" Version="0.9.31" />
    <PackageReference Include="DotNetWorkQueue.Transport.Redis" Version="0.9.31" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>


</Project>
